eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka


spring:
  main:
    allow-bean-definition-overriding: true
  data:
  mongodb:
    host: localhost
    port: 27017
    database: final
    auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: miu.webstore@gmail.com
    password: GFeRyBop5htNjr
    properties:
      mail:
        smtp:
          starttls:
             enable: true
          auth: true
